SELECT C.DEPOSIT_NAME
      ,J.NAME
      ,C.RS
      ,C.SROK_FROM
      ,C.SROK_TO
      ,QUAL$P_MAIN.GET('BAL',B.OBJID,'EXT_CONS_ACC') EXT_CONS_ACC
      ,LL.VALUE ДОГОВОР_ДЛЯ_ПРОЦЕНТОВ
      ,QUAL$P_MAIN.GET('DEPTYP',C.DEPOSIT_ID,'TRANS_COMPL_DEP') TRANS_COMPL_DEP 
      ,(SELECT QUAL$P_MAIN.GET('BAL',BB.OBJID,'EXT_CONS_ACC') FROM GC.BAL BB WHERE BB.BS = QUAL$P_MAIN.GET('DEPTYP',C.DEPOSIT_ID,'CPR_BS',L.FILIAL) AND BB.FILIAL = L.FILIAL AND BB.CUR = '810') ПРОЦЕНТЫ
      ,(SELECT QUAL$P_MAIN.GET('ACC',A.OBJID,'EXT_CONS_ACC') FROM GC.ACC A WHERE A.S = QUAL$P_MAIN.GET('DEPTYP',C.DEPOSIT_ID,'S_D_PROC',L.FILIAL)) ДОХОДЫ
      ,(SELECT QUAL$P_MAIN.GET('ACC',A.OBJID,'EXT_CONS_ACC') FROM GC.ACC A WHERE A.S = QUAL$P_MAIN.GET('DEPTYP',C.DEPOSIT_ID,'S_R_PROC',L.FILIAL)) РАСХОДЫ
      ,QUAL$P_MAIN.GET('DEPTYP',C.DEPOSIT_ID,'KOD_PR') КОД_СХЕМЫ
      ,(SELECT MAX(DATE_B) FROM GC.J_QUAL J WHERE J.OBJID = C.DEPOSIT_ID AND J.NAME = 'KOD_PR') ДАТА_УСТАНОВКИ_ПРОЦ_СХЕМЫ
      ,(SELECT J.TXT FROM GC.J_QUAL J WHERE J.OBJID = C.DEPOSIT_ID AND J.NAME = 'KOD_PR' AND J.DATE_B = (SELECT MAX(JJ.DATE_B) FROM GC.J_QUAL JJ WHERE JJ.OBJID = C.DEPOSIT_ID AND JJ.NAME = 'KOD_PR')) ОБОСНОВАНИЕ
      ,(SELECT MAX(DEPOZIT) FROM GC.SH_PROC WHERE KOD = QUAL$P_MAIN.GET('DEPTYP',C.DEPOSIT_ID,'KOD_PR') AND SUMM = 0) PRC_1
      ,(SELECT MAX(DEPOZIT) FROM GC.SH_PROC WHERE KOD = QUAL$P_MAIN.GET('DEPTYP',C.DEPOSIT_ID,'KOD_PR') AND SUMM = 100) PRC_2
      ,(SELECT MAX(DEPOZIT) FROM GC.SH_PROC WHERE KOD = QUAL$P_MAIN.GET('DEPTYP',C.DEPOSIT_ID,'KOD_PR') AND SUMM = 600) PRC_3
      
         FROM GC.SDM$LIST_DEPOSIT_CC C
             ,GC.L_QUAL L
             ,GC.J_QUAL J
             ,GC.BAL B
             ,GC.L_QUAL LL
             ,GC.L_QUAL LLL

WHERE 1=1
  AND C.DEPOSIT_NAME in ('SHORT-RUB','INVEST-RUB','DOHOD-RUB','CAPIT-RUB')
  AND C.RS IN ('40702','40703','40802')--,'40807')
  AND C.DEPOSIT_ID = L.OBJID(+)
  AND L.FILIAL(+)= 'M'
  AND L.NAME(+)= 'BALS'
  AND J.VALUE(+)= L.OBJID
  AND J.OBJID(+)= 0
  AND J.OBJTYPE(+)= 'DEPTYP'
  AND B.OBJID(+)= L.VALUE
  AND LL.OBJID(+)=L.OBJID
  AND LL.NAME(+)='V_VKL_VNESH_PR'
  AND LLL.OBJID(+)=L.OBJID
  AND LLL.NAME(+)='TRANS_COMPL_DEP'
  ORDER BY 1,3,4;
  
  
  
  
 -- SELECT * FROM GC.J_QUAL



                                  

SELECT C.DEPOSIT_NAME
      ,C.DEPOSIT_ID
      ,J.NAME
      ,C.RS
      ,C.SROK_FROM
      ,C.SROK_TO
      ,QUAL$P_MAIN.GET('BAL',B.OBJID,'EXT_CONS_ACC') EXT_CONS_ACC
      ,LL.VALUE ДОГОВОР_ДЛЯ_ПРОЦЕНТОВ
      ,QUAL$P_MAIN.GET('DEPTYP',C.DEPOSIT_ID,'TRANS_COMPL_DEP') TRANS_COMPL_DEP 
      ,(SELECT QUAL$P_MAIN.GET('BAL',BB.OBJID,'EXT_CONS_ACC') FROM GC.BAL BB WHERE BB.BS = QUAL$P_MAIN.GET('DEPTYP',C.DEPOSIT_ID,'CPR_BS',L.FILIAL) AND BB.FILIAL = L.FILIAL AND BB.CUR = '156') ПРОЦЕНТЫ
      ,(SELECT QUAL$P_MAIN.GET('ACC',A.OBJID,'EXT_CONS_ACC') FROM GC.ACC A WHERE A.S = QUAL$P_MAIN.GET('DEPTYP',C.DEPOSIT_ID,'S_D_PROC_NAT',L.FILIAL)) ДОХОДЫ
      ,(SELECT QUAL$P_MAIN.GET('ACC',A.OBJID,'EXT_CONS_ACC') FROM GC.ACC A WHERE A.S = QUAL$P_MAIN.GET('DEPTYP',C.DEPOSIT_ID,'S_R_PROC_NAT',L.FILIAL)) РАСХОДЫ
      ,QUAL$P_MAIN.GET('DEPTYP',C.DEPOSIT_ID,'KOD_PR',SYSDATE+2,SYSDATE+2,SYSDATE+2) КОД_СХЕМЫ
      ,(SELECT MAX(DATE_B) FROM GC.J_QUAL J WHERE J.OBJID = C.DEPOSIT_ID AND J.NAME = 'KOD_PR') ДАТА_УСТАНОВКИ_ПРОЦ_СХЕМЫ
      ,(SELECT J.TXT FROM GC.J_QUAL J WHERE J.OBJID = C.DEPOSIT_ID AND J.NAME = 'KOD_PR' AND J.DATE_B = (SELECT MAX(JJ.DATE_B) FROM GC.J_QUAL JJ WHERE JJ.OBJID = C.DEPOSIT_ID AND JJ.NAME = 'KOD_PR')) ОБОСНОВАНИЕ
      ,(SELECT MAX(DEPOZIT) FROM GC.SH_PROC WHERE KOD = QUAL$P_MAIN.GET('DEPTYP',C.DEPOSIT_ID,'KOD_PR',SYSDATE+2,SYSDATE+2,SYSDATE+2) AND SUMM = 0) PRC_1
      ,(SELECT MAX(DEPOZIT) FROM GC.SH_PROC WHERE KOD = QUAL$P_MAIN.GET('DEPTYP',C.DEPOSIT_ID,'KOD_PR',SYSDATE+2,SYSDATE+2,SYSDATE+2) AND SUMM = 100) PRC_2
      ,(SELECT MAX(DEPOZIT) FROM GC.SH_PROC WHERE KOD = QUAL$P_MAIN.GET('DEPTYP',C.DEPOSIT_ID,'KOD_PR',SYSDATE+2,SYSDATE+2,SYSDATE+2) AND SUMM = 600) PRC_3
      ,(SELECT MAX(DEPOZIT) FROM GC.SH_PROC WHERE KOD = QUAL$P_MAIN.GET('DEPTYP',C.DEPOSIT_ID,'KOD_PR',SYSDATE+2,SYSDATE+2,SYSDATE+2) AND SUMM = 1000) PRC_4      
      
         FROM GC.SDM$LIST_DEPOSIT_CC C
             ,GC.L_QUAL L
             ,GC.J_QUAL J
             ,GC.BAL B
             ,GC.L_QUAL LL
             ,GC.L_QUAL LLL

WHERE 1=1
  AND C.DEPOSIT_NAME in ('DOHOD-CNY','CAPIT-CNY')
  AND C.RS IN ('40702','40703','40802','40807')
  AND C.DEPOSIT_ID = L.OBJID(+)
  AND L.FILIAL(+)= 'M'
  AND L.NAME(+)= 'BALS'
  AND J.VALUE(+)= L.OBJID
  AND J.OBJID(+)= 0
  AND J.OBJTYPE(+)= 'DEPTYP'
  AND B.OBJID(+)= L.VALUE
  AND LL.OBJID(+)=L.OBJID
  AND LL.NAME(+)='V_VKL_VNESH_PR'
  AND LLL.OBJID(+)=L.OBJID
  AND LLL.NAME(+)='TRANS_COMPL_DEP'
  ORDER BY 1,4,5;
